---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  interval: 5m0s
  path: ./clusters/tbc/kyverno-policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

